import type { Metadata } from "next"
import localFont from "next/font/local"
import {
  ClerkProvider
} from '@clerk/nextjs'
import "./globals.css"
import Header from "./conponents/Header"
import { ThemeProvider } from "next-themes"
import Toggle from "./conponents/Toggle"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <ThemeProvider>
          <Toggle>
            <Header />
            {children}
        </Toggle>
        </ThemeProvider>
        
      </body>
    </html>
    </ClerkProvider>
  );
}
